#!/bin/bash

# We build libzim now
# apt-get install libzim-dev
apt-get install automake autoconf libtool pkg-config icu-devtools libicu-dev libxapian-dev


# Need to be on Debian testing for libgumbo-dev
apt-get install liblzma-dev libmagic-dev zlib1g-dev libgumbo-dev

